FROM neofreko/java8

# Install android SDK
# No need lib32 after android platform-tools 24.+
RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    wget --progress=dot:giga -O /opt/android-sdk.tgz --quiet http://dl.google.com/android/android-sdk_r25.2.5-linux.tgz && \
    tar xzf /opt/android-sdk.tgz -C /opt && \
    rm -rf /opt/android-sdk.tgz && \
    echo y | /opt/android-sdk-linux/tools/android update sdk --all --filter platform-tools,tools,build-tools-26.0.2 --no-ui --force && \
    apt-get clean && \
    rm -fr /var/lib/apt/lists/* /tmp/* /var/tmp/* /opt/android-sdk-linux/temp/*

# Setup environment
ENV ANDROID_HOME /opt/android-sdk-linux
ENV PATH ${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/build-tools/26.0.2

# Check command
RUN which adb
RUN which aapt
RUN which android

# Expose default ADB port
EXPOSE 5037

# Start adb server by default
CMD adb -a -P 5037 server nodaemon

# Build command
# docker build -f Dockerfile-java8-android -t robinluo/java8-android .